/** @jsx jsx */
/** @jsxRuntime classic */
import { jsx } from '@emotion/react';
import React from 'react';

/**
 * This component was generated by exporting a Figma frame using Builder.io Figma to HTML Plugin
 * Figma Plugin: https://www.figma.com/community/plugin/747985167520967365/Figma-to-HTML%2C-CSS%2C-React-%26-more!
 * 
 * After that used @jsx-lite/cli to convert from builder.json format into a React Component
 * jsx-lite compile --to react --from builder page.builder.json
 **/
export default function MyComponent(props) {
  return (
    <>
      <div
        css={{
          display: 'flex',
          flexDirection: 'column',
          maxWidth: '1466.821533203125px',
          justifyContent: 'flex-start',
          alignItems: 'flex-start',
          paddingTop: '50px',
          paddingBottom: '50px',
          paddingRight: '41px',
          paddingLeft: '41px',
          backgroundImage:
            'url("https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Ffb770562be374592b6eb28dcb0799816")',
          backgroundSize: 'cover',
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'center',
        }}
      >
        <div
          css={{
            display: 'flex',
            flexDirection: 'column',
            maxWidth: '1384.821533203125px',
            justifyContent: 'flex-start',
            alignItems: 'flex-start',
          }}
        >
          <div
            css={{
              display: 'flex',
              flexDirection: 'column',
              maxWidth: '1384.821533203125px',
            }}
          >
            <div
              className="builder-columns"
              css={{
                display: 'flex',
                '@media (max-width: 999px)': {
                  flexDirection: 'column',
                  alignItems: 'stretch',
                },
              }}
            >
              <div
                className="builder-column"
                css={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'stretch',
                  lineHeight: 'normal',
                  width: 'calc(33.333333333333336% - 13.333333333333334px)',
                  marginLeft: '0px',
                  '@media (max-width: 999px)': {
                    width: '100%',
                    marginLeft: 0,
                  },
                }}
              >
                <div
                  css={{
                    display: 'flex',
                    position: 'relative',
                    minWidth: '20px',
                    minHeight: '20px',
                    maxWidth: '174.82147216796875px',
                    width: '174.82147216796875px',
                  }}
                >
                  <picture>
                    <source
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a"
                      type="image/webp"
                    />

                    <img
                      src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a"
                      srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F3c68c5f4c526432295dcbd44dd6e7c0a"
                      css={{
                        objectFit: 'contain',
                        objectPosition: 'center',
                        position: 'absolute',
                        height: '100%',
                        width: '100%',
                        top: '0',
                        left: '0',
                      }}
                    />
                  </picture>

                  <div
                    className="builder-image-sizer"
                    css={{
                      width: '100%',
                      paddingTop: '25.74055389234623%',
                      pointerEvents: 'none',
                      fontSize: '0',
                    }}
                  ></div>
                </div>
              </div>

              <div
                className="builder-column"
                css={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'stretch',
                  lineHeight: 'normal',
                  width: 'calc(33.333333333333336% - 13.333333333333334px)',
                  marginLeft: '20px',
                  '@media (max-width: 999px)': {
                    width: '100%',
                    marginLeft: 0,
                  },
                }}
              >
                <div
                  css={{
                    display: 'flex',
                    flexDirection: 'row',
                    maxWidth: '941px',
                    justifyContent: 'center',
                    alignItems: 'stretch',
                    paddingRight: '250px',
                    paddingLeft: '250px',
                  }}
                >
                  <div
                    css={{
                      display: 'flex',
                      flexDirection: 'row',
                      maxWidth: '119px',
                      justifyContent: 'flex-start',
                      alignItems: 'flex-start',
                    }}
                  >
                    <div
                      css={{
                        maxWidth: '95px',
                        color: 'rgba(16, 24, 32, 1)',
                        fontSize: '18px',
                        lineHeight: '30px',
                        letterSpacing: '2%',
                        textAlign: 'left',
                        fontFamily: 'Roboto, sans-serif',
                      }}
                    >
                      PERSONAS
                    </div>

                    <div
                      css={{
                        display: 'flex',
                        flexDirection: 'column',
                        maxWidth: '24px',
                      }}
                    >
                      <div
                        css={{
                          display: 'flex',
                          position: 'relative',
                          minWidth: '20px',
                          minHeight: '20px',
                          maxWidth: '24px',
                          justifyContent: 'flex-start',
                          alignItems: 'flex-start',
                          width: '24px',
                        }}
                      >
                        <picture>
                          <source
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6"
                            type="image/webp"
                          />

                          <img
                            src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb90eef8b937242e3ab6940ccef9c63c6"
                            css={{
                              objectFit: 'contain',
                              objectPosition: 'center',
                              position: 'absolute',
                              height: '100%',
                              width: '100%',
                              top: '0',
                              left: '0',
                            }}
                          />
                        </picture>

                        <div
                          className="builder-image-sizer"
                          css={{
                            width: '100%',
                            paddingTop: '100%',
                            pointerEvents: 'none',
                            fontSize: '0',
                          }}
                        ></div>
                      </div>
                    </div>
                  </div>

                  <div
                    css={{
                      display: 'flex',
                      flexDirection: 'row',
                      maxWidth: '131px',
                      justifyContent: 'flex-start',
                      alignItems: 'flex-start',
                      marginLeft: '30px',
                    }}
                  >
                    <div
                      css={{
                        maxWidth: '107px',
                        color: 'rgba(16, 24, 32, 1)',
                        fontSize: '18px',
                        lineHeight: '30px',
                        letterSpacing: '2%',
                        textAlign: 'left',
                        fontFamily: 'Roboto, sans-serif',
                      }}
                    >
                      TEMPLATES
                    </div>

                    <div
                      css={{
                        display: 'flex',
                        flexDirection: 'column',
                        maxWidth: '24px',
                      }}
                    >
                      <div
                        css={{
                          display: 'flex',
                          position: 'relative',
                          minWidth: '20px',
                          minHeight: '20px',
                          maxWidth: '24px',
                          justifyContent: 'flex-start',
                          alignItems: 'flex-start',
                          width: '24px',
                        }}
                      >
                        <picture>
                          <source
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597"
                            type="image/webp"
                          />

                          <img
                            src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F824aa86fee5f4f638dca4f2f4a7f8597"
                            css={{
                              objectFit: 'contain',
                              objectPosition: 'center',
                              position: 'absolute',
                              height: '100%',
                              width: '100%',
                              top: '0',
                              left: '0',
                            }}
                          />
                        </picture>

                        <div
                          className="builder-image-sizer"
                          css={{
                            width: '100%',
                            paddingTop: '100%',
                            pointerEvents: 'none',
                            fontSize: '0',
                          }}
                        ></div>
                      </div>
                    </div>
                  </div>

                  <div
                    css={{
                      display: 'flex',
                      flexDirection: 'row',
                      maxWidth: '131px',
                      justifyContent: 'flex-start',
                      alignItems: 'flex-start',
                      marginLeft: '30px',
                    }}
                  >
                    <div
                      css={{
                        maxWidth: '107px',
                        color: 'rgba(16, 24, 32, 1)',
                        fontSize: '18px',
                        lineHeight: '30px',
                        letterSpacing: '2%',
                        textAlign: 'left',
                        fontFamily: 'Roboto, sans-serif',
                      }}
                    >
                      RESOURCES
                    </div>

                    <div
                      css={{
                        display: 'flex',
                        flexDirection: 'column',
                        maxWidth: '24px',
                      }}
                    >
                      <div
                        css={{
                          display: 'flex',
                          position: 'relative',
                          minWidth: '20px',
                          minHeight: '20px',
                          maxWidth: '24px',
                          justifyContent: 'flex-start',
                          alignItems: 'flex-start',
                          width: '24px',
                        }}
                      >
                        <picture>
                          <source
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd"
                            type="image/webp"
                          />

                          <img
                            src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd"
                            srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fb98cd20f5c5f4dad961ccf16e6c16fbd"
                            css={{
                              objectFit: 'contain',
                              objectPosition: 'center',
                              position: 'absolute',
                              height: '100%',
                              width: '100%',
                              top: '0',
                              left: '0',
                            }}
                          />
                        </picture>

                        <div
                          className="builder-image-sizer"
                          css={{
                            width: '100%',
                            paddingTop: '100%',
                            pointerEvents: 'none',
                            fontSize: '0',
                          }}
                        ></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div
                className="builder-column"
                css={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'stretch',
                  lineHeight: 'normal',
                  width: 'calc(33.333333333333336% - 13.333333333333334px)',
                  marginLeft: '20px',
                  '@media (max-width: 999px)': {
                    width: '100%',
                    marginLeft: 0,
                  },
                }}
              >
                <div
                  css={{
                    display: 'flex',
                    flexDirection: 'row',
                    maxWidth: '229px',
                    justifyContent: 'flex-end',
                    alignItems: 'stretch',
                  }}
                >
                  <div
                    css={{
                      maxWidth: '62px',
                      color: 'rgba(0, 160, 223, 1)',
                      fontSize: '16px',
                      lineHeight: '30px',
                      letterSpacing: '2%',
                      textAlign: 'center',
                      fontFamily: 'Roboto, sans-serif',
                    }}
                  >
                    LOGIN
                  </div>

                  <div
                    css={{
                      maxWidth: '139px',
                      color: 'rgba(255, 255, 255, 1)',
                      fontSize: '16px',
                      letterSpacing: '-0.14814819395542145px',
                      textAlign: 'center',
                      fontFamily: 'Roboto, sans-serif',
                      display: 'flex',
                      flexDirection: 'row',
                      justifyContent: 'flex-start',
                      alignItems: 'flex-start',
                      marginLeft: '28px',
                      paddingTop: '14px',
                      paddingBottom: '14px',
                      paddingRight: '19px',
                      paddingLeft: '19px',
                      borderColor: 'rgba(255, 135, 0, 1)',
                      borderWidth: '0px',
                      borderStyle: 'solid',
                      backgroundImage:
                        'linear-gradient(to left, rgba(0, 206, 241, 1) 0%, rgba(0, 160, 223, 1) 100%)',
                    }}
                  >
                    GET STARTED
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            css={{
              display: 'flex',
              flexDirection: 'column',
              maxWidth: '535px',
              justifyContent: 'flex-start',
              alignItems: 'flex-start',
              marginTop: '172px',
            }}
          >
            <div
              css={{
                maxWidth: '535px',
                color: 'rgba(16, 24, 32, 1)',
                fontSize: '62px',
                lineHeight: '70px',
                letterSpacing: '0%',
                textAlign: 'left',
                fontFamily: 'Roboto, sans-serif',
              }}
            >
              An easier way to build apps on Kubernetes
            </div>
            <div
              css={{
                display: 'flex',
                flexDirection: 'column',
                maxWidth: '139px',
                justifyContent: 'flex-start',
                alignItems: 'flex-start',
                marginTop: '51px',
              }}
            >
              <div
                css={{
                  maxWidth: '139px',
                  color: 'rgba(255, 255, 255, 1)',
                  fontSize: '16px',
                  letterSpacing: '-0.14814819395542145px',
                  textAlign: 'center',
                  fontFamily: 'Roboto, sans-serif',
                  display: 'flex',
                  flexDirection: 'row',
                  justifyContent: 'flex-start',
                  alignItems: 'flex-start',
                  paddingTop: '14px',
                  paddingBottom: '14px',
                  paddingRight: '19px',
                  paddingLeft: '19px',
                  borderColor: 'rgba(255, 135, 0, 1)',
                  borderWidth: '0px',
                  borderStyle: 'solid',
                  backgroundImage:
                    'linear-gradient(to left, rgba(0, 206, 241, 1) 0%, rgba(0, 160, 223, 1) 100%)',
                }}
              >
                GET STARTED
              </div>
            </div>
            <div
              css={{
                display: 'flex',
                flexDirection: 'column',
                maxWidth: '310px',
                marginTop: '51px',
                borderRadius: '64px',
                paddingTop: '20px',
                paddingBottom: '20px',
                paddingRight: '37px',
                paddingLeft: '37px',
                backgroundColor: 'rgba(255, 255, 255, 0.699999988079071)',
              }}
            >
              <div
                className="builder-columns"
                css={{
                  display: 'flex',
                  '@media (max-width: 999px)': {
                    flexDirection: 'column',
                    alignItems: 'stretch',
                  },
                }}
              >
                <div
                  className="builder-column"
                  css={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    lineHeight: 'normal',
                    width: 'calc(16.666666666666668% - 16.666666666666668px)',
                    marginLeft: '0px',
                    '@media (max-width: 999px)': {
                      width: '100%',
                      marginLeft: 0,
                    },
                  }}
                >
                  <div
                    css={{
                      display: 'flex',
                      position: 'relative',
                      minWidth: '20px',
                      minHeight: '20px',
                      maxWidth: '30px',
                      width: '30px',
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F32dd454dcfb14d258adfa272476f20e5"
                        css={{
                          objectFit: 'cover',
                          objectPosition: 'center',
                          position: 'absolute',
                          height: '100%',
                          width: '100%',
                          top: '0',
                          left: '0',
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: '100%',
                        paddingTop: '100%',
                        pointerEvents: 'none',
                        fontSize: '0',
                      }}
                    ></div>
                  </div>
                </div>

                <div
                  className="builder-column"
                  css={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    lineHeight: 'normal',
                    width: 'calc(16.666666666666668% - 16.666666666666668px)',
                    marginLeft: '20px',
                    '@media (max-width: 999px)': {
                      width: '100%',
                      marginLeft: 0,
                    },
                  }}
                >
                  <div
                    css={{
                      display: 'flex',
                      position: 'relative',
                      minWidth: '20px',
                      minHeight: '20px',
                      maxWidth: '30px',
                      width: '30px',
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fe8e7a9dc7f18451bb43b95060b96e2d6"
                        css={{
                          objectFit: 'cover',
                          objectPosition: 'center',
                          position: 'absolute',
                          height: '100%',
                          width: '100%',
                          top: '0',
                          left: '0',
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: '100%',
                        paddingTop: '93.33333333333333%',
                        pointerEvents: 'none',
                        fontSize: '0',
                      }}
                    ></div>
                  </div>
                </div>

                <div
                  className="builder-column"
                  css={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    lineHeight: 'normal',
                    width: 'calc(16.666666666666668% - 16.666666666666668px)',
                    marginLeft: '20px',
                    '@media (max-width: 999px)': {
                      width: '100%',
                      marginLeft: 0,
                    },
                  }}
                >
                  <div
                    css={{
                      display: 'flex',
                      position: 'relative',
                      minWidth: '20px',
                      minHeight: '20px',
                      maxWidth: '30px',
                      width: '30px',
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fa620f87a3d3447ae96175395c3f412a4"
                        css={{
                          objectFit: 'cover',
                          objectPosition: 'center',
                          position: 'absolute',
                          height: '100%',
                          width: '100%',
                          top: '0',
                          left: '0',
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: '100%',
                        paddingTop: '86.66666666666667%',
                        pointerEvents: 'none',
                        fontSize: '0',
                      }}
                    ></div>
                  </div>
                </div>

                <div
                  className="builder-column"
                  css={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    lineHeight: 'normal',
                    width: 'calc(16.666666666666668% - 16.666666666666668px)',
                    marginLeft: '20px',
                    '@media (max-width: 999px)': {
                      width: '100%',
                      marginLeft: 0,
                    },
                  }}
                >
                  <div
                    css={{
                      display: 'flex',
                      position: 'relative',
                      minWidth: '20px',
                      minHeight: '20px',
                      maxWidth: '30px',
                      width: '30px',
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2Fc46b7b6bbed74f0ea0187d914f994e76"
                        css={{
                          objectFit: 'cover',
                          objectPosition: 'center',
                          position: 'absolute',
                          height: '100%',
                          width: '100%',
                          top: '0',
                          left: '0',
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: '100%',
                        paddingTop: '106.66666666666667%',
                        pointerEvents: 'none',
                        fontSize: '0',
                      }}
                    ></div>
                  </div>
                </div>

                <div
                  className="builder-column"
                  css={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    lineHeight: 'normal',
                    width: 'calc(16.666666666666668% - 16.666666666666668px)',
                    marginLeft: '20px',
                    '@media (max-width: 999px)': {
                      width: '100%',
                      marginLeft: 0,
                    },
                  }}
                >
                  <div
                    css={{
                      display: 'flex',
                      position: 'relative',
                      minWidth: '20px',
                      minHeight: '20px',
                      maxWidth: '38px',
                      width: '38px',
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F76af5a095ee642a9ab3f91aaca38ec3e"
                        css={{
                          objectFit: 'cover',
                          objectPosition: 'center',
                          position: 'absolute',
                          height: '100%',
                          width: '100%',
                          top: '0',
                          left: '0',
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: '100%',
                        paddingTop: '68.42105263157895%',
                        pointerEvents: 'none',
                        fontSize: '0',
                      }}
                    ></div>
                  </div>
                </div>

                <div
                  className="builder-column"
                  css={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'stretch',
                    lineHeight: 'normal',
                    width: 'calc(16.666666666666668% - 16.666666666666668px)',
                    marginLeft: '20px',
                    '@media (max-width: 999px)': {
                      width: '100%',
                      marginLeft: 0,
                    },
                  }}
                >
                  <div
                    css={{
                      display: 'flex',
                      position: 'relative',
                      minWidth: '20px',
                      minHeight: '20px',
                      maxWidth: '28px',
                      width: '28px',
                    }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?format=webp&width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?format=webp&width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?format=webp&width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?format=webp&width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?format=webp&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?format=webp&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?format=webp&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d"
                        type="image/webp"
                      />

                      <img
                        src="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d"
                        srcSet="https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2FTEMP%2F25f681de43f9413c83f0e46ef5a1ef8d"
                        css={{
                          objectFit: 'cover',
                          objectPosition: 'center',
                          position: 'absolute',
                          height: '100%',
                          width: '100%',
                          top: '0',
                          left: '0',
                        }}
                      />
                    </picture>

                    <div
                      className="builder-image-sizer"
                      css={{
                        width: '100%',
                        paddingTop: '75%',
                        pointerEvents: 'none',
                        fontSize: '0',
                      }}
                    ></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
